#!/bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL
 if [[ $regex =~ $email ]];
 then
 echo Your email $email does not satisfy git policy
 exit 1
 else
 echo Your email $email does  satisfy git policy
 exit 0
 fi

